# Generated by Django 5.1.4 on 2025-02-09 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantityInStock', models.IntegerField()),
                ('price', models.FloatField()),
                ('isAvailable', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='MobileMoneyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=100)),
                ('transactionId', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('transactionDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleDate', models.DateField(auto_now_add=True)),
                ('totalAmount', models.FloatField()),
                ('paymentMethod', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CosmeticProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webApp.product')),
                ('brand', models.CharField(max_length=50)),
            ],
            bases=('webApp.product',),
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webApp.product')),
                ('expiryDate', models.DateField()),
            ],
            bases=('webApp.product',),
        ),
        migrations.CreateModel(
            name='SchoolSupplyProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webApp.product')),
                ('supplyType', models.CharField(max_length=100)),
            ],
            bases=('webApp.product',),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billDetails', models.TextField()),
                ('issuedDate', models.DateField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unitPrice', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.sale')),
            ],
        ),
    ]
