# Generated by Django 5.1.4 on 2025-02-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
    ]
