# Generated by Django 5.1.4 on 2025-02-23 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_auto_20250223_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionKey', models.CharField(max_length=40, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mobilemoneyservice',
            name='transactionId',
        ),
        migrations.AlterField(
            model_name='bill',
            name='issuedDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApp.basket'),
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.basket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.product')),
            ],
        ),
    ]
