# Generated by Django 5.1.4 on 2025-02-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_basket_remove_mobilemoneyservice_transactionid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneyservice',
            name='transactionType',
            field=models.CharField(choices=[('Withdraw', 'Withdraw'), ('Send', 'Send')], default='Send', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobilemoneyservice',
            name='serviceName',
            field=models.CharField(choices=[('Flooz', 'Flooz'), ('TMoney', 'TMoney')], max_length=100),
        ),
    ]
