# Generated by Django 5.1.4 on 2025-02-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_mobilemoneyservice_transactiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneyservice',
            name='mobileNumber',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
